name: Reusable workflow

on:
  workflow_call:
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}



#-------------------------------------------


jobs:
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}

jobs:
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }}
