name: Workflow reuitilizable

on:
  workflow_call:

    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.Accion_workflow.outputs.output1 }}
        
    inputs:
      name_runners:
        description: "Nombre del self-hosted"
        required: true
        type: string
        default: 0

jobs:

  Accion_workflow:
  
    name: workflow salidas y entradas
    runs-on: ${{inputs.name_runners}}
    
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      
    steps:
     - id: step1
       run: echo "firstword=hello" >> $GITHUB_OUTPUT
        
     - name: Accion del despliegue 1
       run: | 
         echo "Hola diablo"
