name: test-upload-download

on:
  workflow_dispatch:

jobs:
  test-upload:
    runs-on: ubuntu-latest
    steps:
      - name: create
        run: |
          mkdir -p directorio
          ls -al
          touch directorio/test.txt
          echo "Lineas de pruebas" > directorio/test.txt
          cat directorio/test.txt
    
      - name: Guardar-txt
        uses: actions/upload-artifact@v4
        with:
            name: test
            path: ${{ github.workspace }}/directorio/

  test-download:
     runs-on: ubuntu-latest
     steps:
       - name: consulation_before
         run: |
           ls -al
          
       - name: Descarga-txt
         uses: actions/download-artifact@v4
         with:
           name: test 
           path: ./

       - name: consulation_after
         run: |
           ls -al
