name: Flujo Base

on: 
  workflow_dispatch:

jobs: 
  Compilacion: 
    runs-on: ubuntu-latest
    steps:
      - name: Acci贸n_1
        run: | 
          echo "Acciones por parte de la acci贸n 1"


  Instlacion:
    runs-on: ubuntu-latest
    needs: Compilacion
    steps:
      - name: Acci贸n_2
        run: | 
          echo "Acciones por parte de la acci贸n 2"
