name: Flujo Base B

on:
  workflow_dispatch:

jobs:
  job1:
    uses: sebras450/Herramientas-Actions/.github/workflows/workflow-reutilizable-B.yml@main
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps: 
      - run: echo "Acciones del job 3"
  job4: 
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }}
      
