name: Flujo Base A

on: 
  workflow_dispatch:

jobs:

  Compilacion: 
    runs-on: ubuntu-latest
    steps:
      - name: Acción_1
        run: | 
          echo "Acciones por parte de la acción 1"

  Instalacion:
    runs-on: ubuntu-latest
    needs: Compilacion
    environment: Aprobacion_instalacion
    steps:
      - name: Acción_2
        run: | 
          echo "Acciones por parte de la acción 2"

  Autorizacion_despliegue_A:
    runs-on: ubuntu-latest
    environment: Aprobacion_despliegue_A
    needs: Instalacion
    steps:
      - name: Negocio_A
        run: | 
          echo "Aprobación de acción despliegue A"

  Workflow_reutilizable_despliegue_A:
    needs: Autorizacion_despliegue_A
    uses: sebras450/Herramientas-Actions/.github/workflows/reutilizable_A.yml@main
    with:
      name_runners: ubuntu-latest
